# a list of all allowed items
item-list:
  1:
    - COCOA_BEANS
    - COOKIE
    - MELON_SEEDS
    - LILY_PAD
  2:
    - PUMPKIN_SEEDS
    - PUMPKIN_PIE
    - SALMON
    - COD
  3:
    - SUGAR
    - SUGAR_CANE
    - PAPER
  4:
    - WHITE_DYE
    - ORANGE_DYE
    - MAGENTA_DYE
    - LIGHT_BLUE_DYE
    - YELLOW_DYE
    - LIME_DYE
    - PINK_DYE
    - GRAY_DYE
    - LIGHT_GRAY_DYE
    - CYAN_DYE
    - PURPLE_DYE
    - BLUE_DYE
    - BROWN_DYE
    - GREEN_DYE
    - RED_DYE
    - BLACK_DYE
  5:
    - LAPIS_LAZULI
    - REDSTONE
    - REDSTONE_TORCH
    - EMERALD
  6:
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    - MUSHROOM_STEW
    - BEETROOT
  7:
    - FURNACE_MINECART
    - CHEST_MINECART
    - TNT_MINECART
    - HOPPER_MINECART
  8:
    - GUNPOWDER
    - ENDER_PEARL
    - FERMENTED_SPIDER_EYE
    - BONE
  9:
    - COMPASS
    - FIREWORK_ROCKET
    - MAP
    - ARMOR_STAND
  10:
    - OAK_SAPLING
    - SPRUCE_SAPLING
    - BIRCH_SAPLING
    - ACACIA_SAPLING
  11:
    - NAME_TAG
    - SADDLE
    - SWEET_BERRIES
    - GLOW_BERRIES
  12:
    - MILK_BUCKET
    - WATER_BUCKET
    - LAVA_BUCKET
    - POWDER_SNOW_BUCKET
  13:
    - OAK_SIGN
    - SPRUCE_SIGN
    - BIRCH_SIGN
    - ACACIA_SIGN
  14:
    - PAINTING
    - ITEM_FRAME
    - GLOW_ITEM_FRAME
    - TNT
  15:
    - GOLDEN_SWORD
    - CLOCK
    - GOLDEN_LEGGINGS
    - GOLDEN_CHESTPLATE
  16:
    - GLASS_BOTTLE
    - RED_SAND
    - GRAVEL
    - FLINT
  17:
    - GOLDEN_APPLE
    - GOLDEN_CARROT
    - GLISTERING_MELON_SLICE
  18:
    - FERN
    - GRASS
    - VINE
    - DEAD_BUSH
  19:
    - SNOWBALL
    - EGG
    - CAKE
    - ARROW
  20:
    - LEATHER
    - FEATHER
    - COOKED_PORKCHOP
    - RABBIT_STEW
  21:
    - SEAGRASS
    - KELP
    - DRIED_KELP_BLOCK
    - SEA_PICKLE
  22:
    - MINECART
    - ANVIL
    - IRON_BARS
    - IRON_CHESTPLATE
  23:
    - DIAMOND
    - DIAMOND_HELMET
    - DIAMOND_AXE
    - DIAMOND_HOE
  24:
    - INK_SAC
    - GLOW_INK_SAC
    - BOOK
    - BOOKSHELF
  25:
    - REPEATER
    - ACTIVATOR_RAIL
    - PISTON
    - STICKY_PISTON
  26:
    - OBSIDIAN
    - ENCHANTING_TABLE
    - ENCHANTED_BOOK
    - JUKEBOX
  27:
    - HAY_BLOCK
    - CARROT
    - BAKED_POTATO
    - BREAD
  28:
    - POINTED_DRIPSTONE
    - GLOW_LICHEN
    - AMETHYST_SHARD
    - MOSSY_STONE_BRICKS
  29:
    - STONECUTTER
    - STONECUTTER
    - CARTOGRAPHY_TABLE
    - FLETCHING_TABLE
  30:
    - POLISHED_GRANITE
    - POLISHED_DIORITE
    - POLISHED_ANDESITE
    - POLISHED_DEEPSLATE
  31:
    - BOW
    - SHIELD
    - FISHING_ROD
    - CARROT_ON_A_STICK
  32:
    - LEAD
    - SLIME_BLOCK
    - HONEY_BLOCK
    - BAMBOO
