# a list of all allowed items
item-list:
  easy:
    - ROOTED_DIRT
    - STONE
    - GRANITE
    - POLISHED_GRANITE
    - DIORITE
    - POLISHED_DIORITE
    - ANDESITE
    - POLISHED_ANDESITE
    - DEEPSLATE
    - COBBLED_DEEPSLATE
    - POLISHED_DEEPSLATE
    - CALCITE
    - TUFF
    - DIRT
    - COARSE_DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - CRIMSON_PLANKS
    - WARPED_PLANKS
    - OAK_SAPLING
    - SPRUCE_SAPLING
    - BIRCH_SAPLING
    - JUNGLE_SAPLING
    - ACACIA_SAPLING
    - DARK_OAK_SAPLING
    - SAND
    - GRAVEL
    - OAK_LOG
    - SPRUCE_LOG
    - BIRCH_LOG
    - JUNGLE_LOG
    - ACACIA_LOG
    - DARK_OAK_LOG
    - STRIPPED_OAK_LOG
    - STRIPPED_SPRUCE_LOG
    - STRIPPED_BIRCH_LOG
    - STRIPPED_JUNGLE_LOG
    - STRIPPED_ACACIA_LOG
    - STRIPPED_DARK_OAK_LOG
    - STRIPPED_OAK_WOOD
    - STRIPPED_SPRUCE_WOOD
    - STRIPPED_BIRCH_WOOD
    - STRIPPED_JUNGLE_WOOD
    - STRIPPED_ACACIA_WOOD
    - STRIPPED_DARK_OAK_WOOD
    - OAK_WOOD
    - SPRUCE_WOOD
    - BIRCH_WOOD
    - JUNGLE_WOOD
    - ACACIA_WOOD
    - DARK_OAK_WOOD
    - GLASS
    - SANDSTONE
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - DANDELION
    - POPPY
    - BLUE_ORCHID
    - ALLIUM
    - AZURE_BLUET
    - RED_TULIP
    - ORANGE_TULIP
    - WHITE_TULIP
    - PINK_TULIP
    - OXEYE_DAISY
    - CORNFLOWER
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    - SUGAR_CANE
    - KELP
    - OAK_SLAB
    - SPRUCE_SLAB
    - BIRCH_SLAB
    - JUNGLE_SLAB
    - ACACIA_SLAB
    - DARK_OAK_SLAB
    - STONE_SLAB
    - SMOOTH_STONE_SLAB
    - SANDSTONE_SLAB
    - COBBLESTONE_SLAB
    - STONE_BRICK_SLAB
    - NETHER_BRICK_SLAB
    - TORCH
    - OAK_STAIRS
    - CHEST
    - CRAFTING_TABLE
    - FURNACE
    - LADDER
    - COBBLESTONE_STAIRS
    - SNOW
    - CACTUS
    - CLAY
    - SPRUCE_STAIRS
    - BIRCH_STAIRS
    - JUNGLE_STAIRS
    - COBBLESTONE_WALL
    - GRANITE_WALL
    - STONE_BRICK_WALL
    - ANDESITE_WALL
    - SANDSTONE_WALL
    - DIORITE_WALL
    - WHITE_CARPET
    - ORANGE_CARPET
    - MAGENTA_CARPET
    - LIGHT_BLUE_CARPET
    - YELLOW_CARPET
    - LIME_CARPET
    - PINK_CARPET
    - GRAY_CARPET
    - LIGHT_GRAY_CARPET
    - CYAN_CARPET
    - PURPLE_CARPET
    - BLUE_CARPET
    - BROWN_CARPET
    - GREEN_CARPET
    - RED_CARPET
    - BLACK_CARPET
    - ACACIA_STAIRS
    - DARK_OAK_STAIRS
    - SUNFLOWER
    - LILAC
    - ROSE_BUSH
    - PEONY
    - STONE_STAIRS
    - GRANITE_STAIRS
    - ANDESITE_STAIRS
    - DIORITE_STAIRS
    - GRANITE_SLAB
    - ANDESITE_SLAB
    - DIORITE_SLAB
    - COBBLED_DEEPSLATE_SLAB
    - LEVER
    - STONE_BUTTON
    - OAK_BUTTON
    - SPRUCE_BUTTON
    - BIRCH_BUTTON
    - JUNGLE_BUTTON
    - ACACIA_BUTTON
    - DARK_OAK_BUTTON
    - STONE_PRESSURE_PLATE
    - LIGHT_WEIGHTED_PRESSURE_PLATE
    - HEAVY_WEIGHTED_PRESSURE_PLATE
    - OAK_PRESSURE_PLATE
    - SPRUCE_PRESSURE_PLATE
    - BIRCH_PRESSURE_PLATE
    - JUNGLE_PRESSURE_PLATE
    - ACACIA_PRESSURE_PLATE
    - DARK_OAK_PRESSURE_PLATE
    - OAK_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - OAK_TRAPDOOR
    - SPRUCE_TRAPDOOR
    - BIRCH_TRAPDOOR
    - JUNGLE_TRAPDOOR
    - ACACIA_TRAPDOOR
    - DARK_OAK_TRAPDOOR
    - OAK_FENCE_GATE
    - SPRUCE_FENCE_GATE
    - BIRCH_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - ACACIA_FENCE_GATE
    - DARK_OAK_FENCE_GATE
    - CARROT_ON_A_STICK
    - OAK_BOAT
    - SPRUCE_BOAT
    - BIRCH_BOAT
    - JUNGLE_BOAT
    - ACACIA_BOAT
    - DARK_OAK_BOAT
    - APPLE
    - CHARCOAL
    - WOODEN_SWORD
    - WOODEN_SHOVEL
    - WOODEN_PICKAXE
    - WOODEN_AXE
    - WOODEN_HOE
    - STONE_SWORD
    - STONE_SHOVEL
    - STONE_PICKAXE
    - STONE_AXE
    - STONE_HOE
    - STICK
    - BOWL
    - MUSHROOM_STEW
    - STRING
    - FEATHER
    - GUNPOWDER
    - WHEAT_SEEDS
    - WHEAT
    - BREAD
    - LEATHER_HELMET
    - LEATHER_CHESTPLATE
    - LEATHER_LEGGINGS
    - LEATHER_BOOTS
    - FLINT
    - PORKCHOP
    - COOKED_PORKCHOP
    - PAINTING
    - OAK_SIGN
    - SPRUCE_SIGN
    - BIRCH_SIGN
    - JUNGLE_SIGN
    - ACACIA_SIGN
    - DARK_OAK_SIGN
    - SNOWBALL
    - LEATHER
    - MILK_BUCKET
    - BRICK
    - CLAY_BALL
    - DRIED_KELP_BLOCK
    - PAPER
    - BOOK
    - EGG
    - FISHING_ROD
    - SALMON
    - COOKED_SALMON
    - INK_SAC
    - WHITE_DYE
    - ORANGE_DYE
    - MAGENTA_DYE
    - LIGHT_BLUE_DYE
    - YELLOW_DYE
    - LIME_DYE
    - PINK_DYE
    - GRAY_DYE
    - LIGHT_GRAY_DYE
    - CYAN_DYE
    - PURPLE_DYE
    - BLUE_DYE
    - BROWN_DYE
    - GREEN_DYE
    - RED_DYE
    - BLACK_DYE
    - BONE_MEAL
    - BONE
    - SUGAR
    - WHITE_BED
    - ORANGE_BED
    - MAGENTA_BED
    - LIGHT_BLUE_BED
    - YELLOW_BED
    - LIME_BED
    - PINK_BED
    - GRAY_BED
    - LIGHT_GRAY_BED
    - CYAN_BED
    - PURPLE_BED
    - BLUE_BED
    - BROWN_BED
    - GREEN_BED
    - RED_BED
    - BLACK_BED
    - MELON_SLICE
    - DRIED_KELP
    - PUMPKIN_SEEDS
    - MELON_SEEDS
    - BEEF
    - COOKED_BEEF
    - CHICKEN
    - COOKED_CHICKEN
    - ROTTEN_FLESH
    - GLASS_BOTTLE
    - SPIDER_EYE
    - MUTTON
    - COOKED_MUTTON
    - WHITE_BANNER
    - ORANGE_BANNER
    - MAGENTA_BANNER
    - LIGHT_BLUE_BANNER
    - YELLOW_BANNER
    - LIME_BANNER
    - PINK_BANNER
    - GRAY_BANNER
    - LIGHT_GRAY_BANNER
    - CYAN_BANNER
    - PURPLE_BANNER
    - BLUE_BANNER
    - BROWN_BANNER
    - GREEN_BANNER
    - RED_BANNER
    - BLACK_BANNER
    - BARREL
    - OAK_FENCE
    - SPRUCE_FENCE
    - BIRCH_FENCE
    - JUNGLE_FENCE
    - ACACIA_FENCE
    - DARK_OAK_FENCE
    - PUMPKIN
  normal:
    - CARVED_PUMPKIN
    - DRIPSTONE_BLOCK
    - RED_SAND
    - COAL_BLOCK
    - RAW_IRON_BLOCK
    - RAW_COPPER_BLOCK
    - RAW_GOLD_BLOCK
    - IRON_BLOCK
    - COPPER_BLOCK
    - GOLD_BLOCK
    - NETHERITE_BLOCK
    - CUT_COPPER
    - CUT_COPPER_STAIRS
    - CUT_COPPER_SLAB
    - WAXED_COPPER_BLOCK
    - WAXED_CUT_COPPER
    - WAXED_CUT_COPPER_STAIRS
    - WAXED_CUT_COPPER_SLAB
    - OAK_LEAVES
    - SPRUCE_LEAVES
    - BIRCH_LEAVES
    - JUNGLE_LEAVES
    - ACACIA_LEAVES
    - DARK_OAK_LEAVES
    - TINTED_GLASS
    - LAPIS_BLOCK
    - COBWEB
    - GRASS
    - FERN
    - AZALEA
    - DEAD_BUSH
    - SEAGRASS
    - SEA_PICKLE
    - BAMBOO
    - BRICK_SLAB
    - RED_SANDSTONE_SLAB
    - CUT_RED_SANDSTONE_SLAB
    - SMOOTH_RED_SANDSTONE
    - SMOOTH_SANDSTONE
    - SMOOTH_STONE
    - BRICKS
    - BOOKSHELF
    - MOSSY_COBBLESTONE
    - SNOW_BLOCK
    - SANDSTONE_STAIRS
    - MOSSY_COBBLESTONE_WALL
    - BRICK_WALL
    - RED_SANDSTONE_WALL
    - MOSSY_STONE_BRICK_WALL
    - COBBLED_DEEPSLATE_WALL
    - POLISHED_DEEPSLATE_WALL
    - DEEPSLATE_BRICK_WALL
    - DEEPSLATE_TILE_WALL
    - ANVIL
    - CHIPPED_ANVIL
    - DAMAGED_ANVIL
    - WHITE_TERRACOTTA
    - ORANGE_TERRACOTTA
    - MAGENTA_TERRACOTTA
    - LIGHT_BLUE_TERRACOTTA
    - YELLOW_TERRACOTTA
    - LIME_TERRACOTTA
    - PINK_TERRACOTTA
    - GRAY_TERRACOTTA
    - LIGHT_GRAY_TERRACOTTA
    - CYAN_TERRACOTTA
    - PURPLE_TERRACOTTA
    - BLUE_TERRACOTTA
    - BROWN_TERRACOTTA
    - GREEN_TERRACOTTA
    - RED_TERRACOTTA
    - BLACK_TERRACOTTA
    - HAY_BLOCK
    - LARGE_FERN
    - WHITE_STAINED_GLASS
    - ORANGE_STAINED_GLASS
    - MAGENTA_STAINED_GLASS
    - LIGHT_BLUE_STAINED_GLASS
    - YELLOW_STAINED_GLASS
    - LIME_STAINED_GLASS
    - PINK_STAINED_GLASS
    - GRAY_STAINED_GLASS
    - LIGHT_GRAY_STAINED_GLASS
    - CYAN_STAINED_GLASS
    - PURPLE_STAINED_GLASS
    - BLUE_STAINED_GLASS
    - BROWN_STAINED_GLASS
    - GREEN_STAINED_GLASS
    - RED_STAINED_GLASS
    - BLACK_STAINED_GLASS
    - RED_SANDSTONE
    - RED_SANDSTONE_STAIRS
    - BONE_BLOCK
    - WHITE_GLAZED_TERRACOTTA
    - ORANGE_GLAZED_TERRACOTTA
    - MAGENTA_GLAZED_TERRACOTTA
    - LIGHT_BLUE_GLAZED_TERRACOTTA
    - YELLOW_GLAZED_TERRACOTTA
    - LIME_GLAZED_TERRACOTTA
    - PINK_GLAZED_TERRACOTTA
    - GRAY_GLAZED_TERRACOTTA
    - LIGHT_GRAY_GLAZED_TERRACOTTA
    - CYAN_GLAZED_TERRACOTTA
    - PURPLE_GLAZED_TERRACOTTA
    - BLUE_GLAZED_TERRACOTTA
    - BROWN_GLAZED_TERRACOTTA
    - GREEN_GLAZED_TERRACOTTA
    - RED_GLAZED_TERRACOTTA
    - BLACK_GLAZED_TERRACOTTA
    - WHITE_CONCRETE
    - ORANGE_CONCRETE
    - MAGENTA_CONCRETE
    - LIGHT_BLUE_CONCRETE
    - YELLOW_CONCRETE
    - LIME_CONCRETE
    - PINK_CONCRETE
    - GRAY_CONCRETE
    - LIGHT_GRAY_CONCRETE
    - CYAN_CONCRETE
    - PURPLE_CONCRETE
    - BLUE_CONCRETE
    - BROWN_CONCRETE
    - GREEN_CONCRETE
    - RED_CONCRETE
    - BLACK_CONCRETE
    - WHITE_CONCRETE_POWDER
    - ORANGE_CONCRETE_POWDER
    - MAGENTA_CONCRETE_POWDER
    - LIGHT_BLUE_CONCRETE_POWDER
    - YELLOW_CONCRETE_POWDER
    - LIME_CONCRETE_POWDER
    - PINK_CONCRETE_POWDER
    - GRAY_CONCRETE_POWDER
    - LIGHT_GRAY_CONCRETE_POWDER
    - CYAN_CONCRETE_POWDER
    - PURPLE_CONCRETE_POWDER
    - BLUE_CONCRETE_POWDER
    - BROWN_CONCRETE_POWDER
    - GREEN_CONCRETE_POWDER
    - RED_CONCRETE_POWDER
    - BLACK_CONCRETE_POWDER
    - DEAD_TUBE_CORAL_BLOCK
    - DEAD_BRAIN_CORAL_BLOCK
    - DEAD_BUBBLE_CORAL_BLOCK
    - DEAD_FIRE_CORAL_BLOCK
    - DEAD_HORN_CORAL_BLOCK
    - TUBE_CORAL_BLOCK
    - BRAIN_CORAL_BLOCK
    - BUBBLE_CORAL_BLOCK
    - FIRE_CORAL_BLOCK
    - HORN_CORAL_BLOCK
    - TUBE_CORAL
    - BRAIN_CORAL
    - BUBBLE_CORAL
    - FIRE_CORAL
    - HORN_CORAL
    - DEAD_BRAIN_CORAL
    - DEAD_BUBBLE_CORAL
    - DEAD_FIRE_CORAL
    - DEAD_HORN_CORAL
    - DEAD_TUBE_CORAL
    - TUBE_CORAL_FAN
    - BRAIN_CORAL_FAN
    - BUBBLE_CORAL_FAN
    - FIRE_CORAL_FAN
    - HORN_CORAL_FAN
    - DEAD_TUBE_CORAL_FAN
    - DEAD_BRAIN_CORAL_FAN
    - DEAD_BUBBLE_CORAL_FAN
    - DEAD_FIRE_CORAL_FAN
    - DEAD_HORN_CORAL_FAN
    - POLISHED_GRANITE_STAIRS
    - SMOOTH_RED_SANDSTONE_STAIRS
    - MOSSY_STONE_BRICK_STAIRS
    - POLISHED_DIORITE_STAIRS
    - MOSSY_COBBLESTONE_STAIRS
    - SMOOTH_SANDSTONE_STAIRS
    - POLISHED_ANDESITE_STAIRS
    - COBBLED_DEEPSLATE_STAIRS
    - POLISHED_DEEPSLATE_STAIRS
    - DEEPSLATE_BRICK_STAIRS
    - DEEPSLATE_TILE_STAIRS
    - POLISHED_GRANITE_SLAB
    - SMOOTH_RED_SANDSTONE_SLAB
    - MOSSY_STONE_BRICK_SLAB
    - POLISHED_DIORITE_SLAB
    - MOSSY_COBBLESTONE_SLAB
    - SMOOTH_SANDSTONE_SLAB
    - SMOOTH_QUARTZ_SLAB
    - POLISHED_ANDESITE_SLAB
    - POLISHED_DEEPSLATE_SLAB
    - DEEPSLATE_BRICK_SLAB
    - DEEPSLATE_TILE_SLAB
    - SCAFFOLDING
    - REDSTONE
    - REDSTONE_TORCH
    - REDSTONE_BLOCK
    - REPEATER
    - COMPARATOR
    - PISTON
    - HOPPER
    - DISPENSER
    - DROPPER
    - LECTERN
    - TARGET
    - LIGHTNING_ROD
    - TRIPWIRE_HOOK
    - TRAPPED_CHEST
    - TNT
    - NOTE_BLOCK
    - IRON_DOOR
    - IRON_TRAPDOOR
    - POWERED_RAIL
    - DETECTOR_RAIL
    - RAIL
    - ACTIVATOR_RAIL
    - SADDLE
    - MINECART
    - CHEST_MINECART
    - FURNACE_MINECART
    - TNT_MINECART
    - HOPPER_MINECART
    - SCUTE
    - FLINT_AND_STEEL
    - BOW
    - ARROW
    - COAL
    - LAPIS_LAZULI
    - RAW_IRON
    - IRON_INGOT
    - RAW_COPPER
    - COPPER_INGOT
    - RAW_GOLD
    - GOLD_INGOT
    - GOLDEN_SWORD
    - GOLDEN_SHOVEL
    - GOLDEN_PICKAXE
    - GOLDEN_AXE
    - GOLDEN_HOE
    - IRON_SWORD
    - IRON_SHOVEL
    - IRON_PICKAXE
    - IRON_AXE
    - IRON_HOE
    - CHAINMAIL_HELMET
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_LEGGINGS
    - CHAINMAIL_BOOTS
    - IRON_HELMET
    - IRON_CHESTPLATE
    - IRON_LEGGINGS
    - IRON_BOOTS
    - GOLDEN_HELMET
    - GOLDEN_CHESTPLATE
    - GOLDEN_LEGGINGS
    - GOLDEN_BOOTS
    - GOLDEN_APPLE
    - BUCKET
    - WATER_BUCKET
    - LAVA_BUCKET
    - PUFFERFISH_BUCKET
    - SALMON_BUCKET
    - COD_BUCKET
    - TROPICAL_FISH_BUCKET
    - AXOLOTL_BUCKET
    - SLIME_BALL
    - COMPASS
    - BUNDLE
    - CLOCK
    - COD
    - TROPICAL_FISH
    - PUFFERFISH
    - COOKED_COD
    - GLOW_INK_SAC
    - COCOA_BEANS
    - CAKE
    - COOKIE
    - FILLED_MAP
    - SHEARS
    - FERMENTED_SPIDER_EYE
    - GLISTERING_MELON_SLICE
    - WRITABLE_BOOK
    - WRITTEN_BOOK
    - ITEM_FRAME
    - FLOWER_POT
    - CARROT
    - POTATO
    - BAKED_POTATO
    - POISONOUS_POTATO
    - MAP
    - GOLDEN_CARROT
    - PUMPKIN_PIE
    - FIREWORK_ROCKET
    - FIREWORK_STAR
    - COOKED_RABBIT
    - RABBIT_STEW
    - RABBIT_FOOT
    - RABBIT_HIDE
    - ARMOR_STAND
    - LEAD
    - BEETROOT
    - BEETROOT_SEEDS
    - BEETROOT_SOUP
    - SHIELD
    - IRON_NUGGET
    - LOOM
    - COMPOSTER
    - SMOKER
    - BLAST_FURNACE
    - CARTOGRAPHY_TABLE
    - FLETCHING_TABLE
    - GRINDSTONE
    - SMITHING_TABLE
    - STONECUTTER
    - BELL
    - LANTERN
    - SWEET_BERRIES
    - CAMPFIRE
    - HONEYCOMB
    - BEE_NEST
    - BEEHIVE
    - HONEY_BOTTLE
    - HONEYCOMB_BLOCK
    - CANDLE
    - WHITE_CANDLE
    - ORANGE_CANDLE
    - MAGENTA_CANDLE
    - LIGHT_BLUE_CANDLE
    - YELLOW_CANDLE
    - LIME_CANDLE
    - PINK_CANDLE
    - GRAY_CANDLE
    - LIGHT_GRAY_CANDLE
    - CYAN_CANDLE
    - PURPLE_CANDLE
    - BLUE_CANDLE
    - BROWN_CANDLE
    - GREEN_CANDLE
    - RED_CANDLE
    - BLACK_CANDLE
    - POINTED_DRIPSTONE
    - COCOA
    - STONE_BRICKS
    - MOSSY_STONE_BRICKS
    - DEEPSLATE_BRICKS
    - CHAIN
    - VINE
    - GLOW_LICHEN
  hard:
    - ANCIENT_DEBRIS
    - AMETHYST_BLOCK
    - BUDDING_AMETHYST
    - DIAMOND_BLOCK
    - CRIMSON_STEM
    - WARPED_STEM
    - STRIPPED_CRIMSON_STEM
    - STRIPPED_WARPED_STEM
    - STRIPPED_CRIMSON_HYPHAE
    - STRIPPED_WARPED_HYPHAE
    - CRIMSON_HYPHAE
    - WARPED_HYPHAE
    - CRIMSON_FUNGUS
    - WARPED_FUNGUS
    - CRIMSON_ROOTS
    - WARPED_ROOTS
    - NETHER_SPROUTS
    - WEEPING_VINES
    - TWISTING_VINES
    - CRIMSON_SLAB
    - WARPED_SLAB
    - QUARTZ_SLAB
    - SMOOTH_QUARTZ
    - OBSIDIAN
    - JUKEBOX
    - NETHER_BRICKS
    - NETHER_BRICK_FENCE
    - NETHER_BRICK_STAIRS
    - ENCHANTING_TABLE
    - ENDER_CHEST
    - EMERALD_BLOCK
    - CRIMSON_STAIRS
    - WARPED_STAIRS
    - NETHER_BRICK_WALL
    - RED_NETHER_BRICK_WALL
    - BLACKSTONE_WALL
    - QUARTZ_BLOCK
    - QUARTZ_BRICKS
    - QUARTZ_PILLAR
    - QUARTZ_STAIRS
    - PACKED_ICE
    - MAGMA_BLOCK
    - NETHER_WART_BLOCK
    - WARPED_WART_BLOCK
    - RED_NETHER_BRICKS
    - TURTLE_EGG
    - BLUE_ICE
    - SMOOTH_QUARTZ_STAIRS
    - RED_NETHER_BRICK_STAIRS
    - RED_NETHER_BRICK_SLAB
    - STICKY_PISTON
    - SLIME_BLOCK
    - HONEY_BLOCK
    - OBSERVER
    - DAYLIGHT_DETECTOR
    - SCULK_SENSOR
    - REDSTONE_LAMP
    - POLISHED_BLACKSTONE_BUTTON
    - CRIMSON_BUTTON
    - WARPED_BUTTON
    - POLISHED_BLACKSTONE_PRESSURE_PLATE
    - CRIMSON_PRESSURE_PLATE
    - WARPED_PRESSURE_PLATE
    - CRIMSON_DOOR
    - WARPED_DOOR
    - CRIMSON_TRAPDOOR
    - WARPED_TRAPDOOR
    - CRIMSON_FENCE_GATE
    - WARPED_FENCE_GATE
    - TURTLE_HELMET
    - DIAMOND
    - EMERALD
    - QUARTZ
    - NETHERITE_INGOT
    - NETHERITE_SCRAP
    - DIAMOND_SWORD
    - DIAMOND_SHOVEL
    - DIAMOND_PICKAXE
    - DIAMOND_AXE
    - DIAMOND_HOE
    - NETHERITE_SWORD
    - NETHERITE_SHOVEL
    - NETHERITE_PICKAXE
    - NETHERITE_AXE
    - NETHERITE_HOE
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS
    - NETHERITE_HELMET
    - NETHERITE_CHESTPLATE
    - NETHERITE_LEGGINGS
    - NETHERITE_BOOTS
    - CRIMSON_SIGN
    - WARPED_SIGN
    - SPYGLASS
    - GLOWSTONE_DUST
    - ENDER_PEARL
    - BLAZE_ROD
    - GHAST_TEAR
    - GOLD_NUGGET
    - NETHER_WART
    - POTION
    - BLAZE_POWDER
    - BREWING_STAND
    - ENDER_EYE
    - ENCHANTED_BOOK
    - NETHER_BRICK
    - PRISMARINE_SHARD
    - PRISMARINE_CRYSTALS
    - IRON_HORSE_ARMOR
    - GOLDEN_HORSE_ARMOR
    - DIAMOND_HORSE_ARMOR
    - LEATHER_HORSE_ARMOR
    - NAME_TAG
    - SPLASH_POTION
    - SPECTRAL_ARROW
    - TIPPED_ARROW
    - TRIDENT
    - NAUTILUS_SHELL
    - CROSSBOW
    - SUSPICIOUS_STEW
    - FLOWER_BANNER_PATTERN
    - CREEPER_BANNER_PATTERN
    - SKULL_BANNER_PATTERN
    - MOJANG_BANNER_PATTERN
    - GLOBE_BANNER_PATTERN
    - PIGLIN_BANNER_PATTERN
    - SOUL_LANTERN
    - GLOW_BERRIES
    - SOUL_CAMPFIRE
    - SHROOMLIGHT
    - LODESTONE
    - CRYING_OBSIDIAN
    - BLACKSTONE
    - BLACKSTONE_SLAB
    - BLACKSTONE_STAIRS
    - GILDED_BLACKSTONE
    - POLISHED_BLACKSTONE
    - POLISHED_BLACKSTONE_SLAB
    - POLISHED_BLACKSTONE_STAIRS
    - POLISHED_BLACKSTONE_BRICKS
    - POLISHED_BLACKSTONE_BRICK_SLAB
    - POLISHED_BLACKSTONE_BRICK_STAIRS
    - RESPAWN_ANCHOR
    - CRIMSON_FENCE
    - WARPED_FENCE
    - SOUL_SAND
    - SOUL_SOIL
    - BASALT
    - SOUL_TORCH
    - GLOWSTONE
  impossible:
    - GRASS_BLOCK
    - PODZOL
    - CRIMSON_NYLIUM
    - WARPED_NYLIUM
    - COAL_ORE
    - DEEPSLATE_COAL_ORE
    - IRON_ORE
    - DEEPSLATE_IRON_ORE
    - COPPER_ORE
    - DEEPSLATE_COPPER_ORE
    - GOLD_ORE
    - DEEPSLATE_GOLD_ORE
    - REDSTONE_ORE
    - DEEPSLATE_REDSTONE_ORE
    - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE
    - LAPIS_ORE
    - DEEPSLATE_LAPIS_ORE
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - NETHER_GOLD_ORE
    - NETHER_QUARTZ_ORE
    - SPONGE
    - WET_SPONGE
    - WITHER_ROSE
    - PRISMARINE_SLAB
    - PRISMARINE_BRICK_SLAB
    - DARK_PRISMARINE_SLAB
    - FARMLAND
    - ICE
    - DIRT_PATH
    - PRISMARINE
    - PRISMARINE_BRICKS
    - DARK_PRISMARINE
    - PRISMARINE_STAIRS
    - PRISMARINE_BRICK_STAIRS
    - DARK_PRISMARINE_STAIRS
    - SEA_LANTERN
    - CONDUIT
    - EXPERIENCE_BOTTLE
    - SKELETON_SKULL
    - WITHER_SKELETON_SKULL
    - ZOMBIE_HEAD
    - CREEPER_HEAD
    - TOTEM_OF_UNDYING
    - PHANTOM_MEMBRANE
    - HEART_OF_THE_SEA
    - BROWN_MUSHROOM_BLOCK
    - RED_MUSHROOM_BLOCK
    - MUSHROOM_STEM
