# a list of all allowed items
item-list:
  length: 40
  1: # cocoa
    - COCOA_BEANS
    - COOKIE
  2: # melon
    - MELON_SEEDS
    - MELON_SLICE
    - MELON
  3: # natural
    - LILY_PAD
    - VINE
    - FERN
    - GRASS
    - DEAD_BUSH
    - BAMBOO
    - SWEET_BERRIES
    - CACTUS
  4: # pumpkin
    - CARVED_PUMPKIN
    - PUMPKIN_SEEDS
    - PUMPKIN_PIE
    - PUMPKIN
    - JACK_O_LANTERN
  5: # fish
    - SALMON
    - SALMON_BUCKET
    - COOKED_SALMON
    - COD
    - COD_BUCKET
    - COOKED_COD
    - PUFFERFISH
    - TROPICAL_FISH
  6: # sugar cane
    - SUGAR
    - SUGAR_CANE
    - PAPER
    - BOOK
    - BOOKSHELF
    - WRITABLE_BOOK
  7: # dye
    - WHITE_DYE
    - ORANGE_DYE
    - MAGENTA_DYE
    - LIGHT_BLUE_DYE
    - YELLOW_DYE
    - LIME_DYE
    - PINK_DYE
    - GRAY_DYE
    - LIGHT_GRAY_DYE
    - CYAN_DYE
    - PURPLE_DYE
    - BLUE_DYE
    - BROWN_DYE
    - GREEN_DYE
    - RED_DYE
    - BLACK_DYE
  8: # wool
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - WHITE_CARPET
    - ORANGE_CARPET
    - MAGENTA_CARPET
    - LIGHT_BLUE_CARPET
    - YELLOW_CARPET
    - LIME_CARPET
    - PINK_CARPET
    - GRAY_CARPET
    - LIGHT_GRAY_CARPET
    - CYAN_CARPET
    - PURPLE_CARPET
    - BLUE_CARPET
    - BROWN_CARPET
    - GREEN_CARPET
    - RED_CARPET
    - BLACK_CARPET
  9: # clay
    - CLAY
    - CLAY_BALL
    - BRICK
    - BRICKS
    - BRICK_SLAB
    - BRICK_WALL
    - BRICK_STAIRS
    - FLOWER_POT
  10: # stones
    # andesite
    - ANDESITE
    - ANDESITE_WALL
    - ANDESITE_SLAB
    - ANDESITE_STAIRS
    - POLISHED_ANDESITE
    - POLISHED_ANDESITE_SLAB
    - POLISHED_ANDESITE_STAIRS
    # diorite
    - DIORITE
    - DIORITE_WALL
    - DIORITE_SLAB
    - DIORITE_STAIRS
    - POLISHED_DIORITE
    - POLISHED_DIORITE_SLAB
    - POLISHED_DIORITE_STAIRS
    # granite
    - GRANITE
    - GRANITE_WALL
    - GRANITE_SLAB
    - GRANITE_STAIRS
    - POLISHED_GRANITE
    - POLISHED_GRANITE_SLAB
    - POLISHED_GRANITE_STAIRS
    # deepslate
    - DEEPSLATE
    - DEEPSLATE_BRICKS
    - DEEPSLATE_BRICK_WALL
    - DEEPSLATE_BRICK_SLAB
    - DEEPSLATE_BRICK_STAIRS
    - DEEPSLATE_TILES
    - DEEPSLATE_TILE_WALL
    - DEEPSLATE_TILE_SLAB
    - DEEPSLATE_TILE_STAIRS
    - COBBLED_DEEPSLATE
    - COBBLED_DEEPSLATE_WALL
    - COBBLED_DEEPSLATE_SLAB
    - COBBLED_DEEPSLATE_STAIRS
    - POLISHED_DEEPSLATE
    - POLISHED_DEEPSLATE_WALL
    - POLISHED_DEEPSLATE_SLAB
    - POLISHED_DEEPSLATE_STAIRS
    - CRACKED_DEEPSLATE_TILES
    - CRACKED_DEEPSLATE_BRICKS
    - CHISELED_DEEPSLATE
    # other
    - CALCITE
    - TUFF
    - MOSSY_STONE_BRICKS
    - MOSSY_COBBLESTONE
    - MOSSY_STONE_BRICKS
    - MOSSY_STONE_BRICK_WALL
    - MOSSY_STONE_BRICK_STAIRS
    - MOSSY_COBBLESTONE_STAIRS
    - MOSSY_STONE_BRICK_SLAB
    - MOSSY_COBBLESTONE_SLAB
  11: # sand
    - SAND
    - SANDSTONE
    - SANDSTONE_WALL
    - SANDSTONE_SLAB
    - SANDSTONE_STAIRS
    - CUT_SANDSTONE
    - CUT_SANDSTONE_SLAB
    - SMOOTH_SANDSTONE
    - SMOOTH_SANDSTONE_SLAB
    - SMOOTH_SANDSTONE_STAIRS
    - RED_SAND
    - RED_SANDSTONE
    - RED_SANDSTONE_WALL
    - RED_SANDSTONE_SLAB
    - RED_SANDSTONE_STAIRS
    - CUT_RED_SANDSTONE
    - CUT_RED_SANDSTONE_SLAB
    - CHISELED_SANDSTONE
    - SMOOTH_RED_SANDSTONE
    - SMOOTH_RED_SANDSTONE_SLAB
    - SMOOTH_RED_SANDSTONE_STAIRS
    - CHISELED_RED_SANDSTONE
  12: # ore
    - CHARCOAL
    - LAPIS_LAZULI
    - EMERALD
    - DIAMOND
    - RAW_IRON_BLOCK
    - RAW_COPPER_BLOCK
    - RAW_GOLD_BLOCK
    - COAL_BLOCK
    - COPPER_BLOCK
    - IRON_BLOCK
    - GOLD_BLOCK
    - LAPIS_BLOCK
    - IRON_NUGGET
    - GOLD_NUGGET
    - GOLD_INGOT
    - IRON_INGOT
    - COPPER_INGOT
    - AMETHYST_SHARD
  13: # minecart
    - MINECART
    - FURNACE_MINECART
    - CHEST_MINECART
    - TNT_MINECART
    - HOPPER_MINECART
  14: # redstone
    - REDSTONE
    - REDSTONE_TORCH
    - REDSTONE_BLOCK
    - CLOCK
    - COMPASS
    - PISTON
    - REPEATER
    - NOTE_BLOCK
    - TARGET
    - LEVER
    - DISPENSER
    - DROPPER
  15: # terracotta
    - TERRACOTTA
    - WHITE_TERRACOTTA
    - ORANGE_TERRACOTTA
    - MAGENTA_TERRACOTTA
    - LIGHT_BLUE_TERRACOTTA
    - YELLOW_TERRACOTTA
    - LIME_TERRACOTTA
    - PINK_TERRACOTTA
    - GRAY_TERRACOTTA
    - LIGHT_GRAY_TERRACOTTA
    - CYAN_TERRACOTTA
    - PURPLE_TERRACOTTA
    - BLUE_TERRACOTTA
    - BROWN_TERRACOTTA
    - GREEN_TERRACOTTA
    - RED_TERRACOTTA
    - BLACK_TERRACOTTA
    - WHITE_GLAZED_TERRACOTTA
    - ORANGE_GLAZED_TERRACOTTA
    - MAGENTA_GLAZED_TERRACOTTA
    - LIGHT_BLUE_GLAZED_TERRACOTTA
    - YELLOW_GLAZED_TERRACOTTA
    - LIME_GLAZED_TERRACOTTA
    - PINK_GLAZED_TERRACOTTA
    - GRAY_GLAZED_TERRACOTTA
    - LIGHT_GRAY_GLAZED_TERRACOTTA
    - CYAN_GLAZED_TERRACOTTA
    - PURPLE_GLAZED_TERRACOTTA
    - BLUE_GLAZED_TERRACOTTA
    - BROWN_GLAZED_TERRACOTTA
    - GREEN_GLAZED_TERRACOTTA
    - RED_GLAZED_TERRACOTTA
    - BLACK_GLAZED_TERRACOTTA
  16: # concrete
    - WHITE_CONCRETE
    - ORANGE_CONCRETE
    - MAGENTA_CONCRETE
    - LIGHT_BLUE_CONCRETE
    - YELLOW_CONCRETE
    - LIME_CONCRETE
    - PINK_CONCRETE
    - GRAY_CONCRETE
    - LIGHT_GRAY_CONCRETE
    - CYAN_CONCRETE
    - PURPLE_CONCRETE
    - BLUE_CONCRETE
    - BROWN_CONCRETE
    - GREEN_CONCRETE
    - RED_CONCRETE
    - BLACK_CONCRETE
    - WHITE_CONCRETE_POWDER
    - ORANGE_CONCRETE_POWDER
    - MAGENTA_CONCRETE_POWDER
    - LIGHT_BLUE_CONCRETE_POWDER
    - YELLOW_CONCRETE_POWDER
    - LIME_CONCRETE_POWDER
    - PINK_CONCRETE_POWDER
    - GRAY_CONCRETE_POWDER
    - LIGHT_GRAY_CONCRETE_POWDER
    - CYAN_CONCRETE_POWDER
    - PURPLE_CONCRETE_POWDER
    - BLUE_CONCRETE_POWDER
    - BROWN_CONCRETE_POWDER
    - GREEN_CONCRETE_POWDER
    - RED_CONCRETE_POWDER
    - BLACK_CONCRETE_POWDER
  17: # slime
    - SLIME_BALL
    - SLIME_BLOCK
    - STICKY_PISTON
    - LEAD
  18: # string
    - STRING
    - BOW
    - FISHING_ROD
    - CARROT_ON_A_STICK
  19: # standard mobs
    - ROTTEN_FLESH
    - BONE
    - BONE_MEAL
    - BONE_BLOCK
    - SPIDER_EYE
    - FERMENTED_SPIDER_EYE
    - GUNPOWDER
    - FIREWORK_ROCKET
  20: # special creature
    - ENDER_PEARL
    - INK_SAC
    - GLOW_INK_SAC
  21: # animals
    - PORKCHOP
    - COOKED_PORKCHOP
    - BEEF
    - COOKED_BEEF
    - CHICKEN
    - COOKED_CHICKEN
    - RABBIT
    - COOKED_RABBIT
    - MUTTON
    - COOKED_MUTTON
    - FEATHER
    - RABBIT_STEW
    - RABBIT_FOOT
    - RABBIT_HIDE
    - EGG
    - HONEY_BOTTLE
  22: # leather
    - LEATHER
    - LEATHER_HELMET
    - LEATHER_CHESTPLATE
    - LEATHER_LEGGINGS
    - LEATHER_BOOTS
    - LEATHER_HORSE_ARMOR
  23: # mushroom
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    - MUSHROOM_STEW
  24: # farming
    - WHEAT_SEEDS
    - WHEAT
    - BREAD
    - CARROT
    - POTATO
    - BAKED_POTATO
    - POISONOUS_POTATO
    - BEETROOT
    - BEETROOT_SEEDS
    - BEETROOT_SOUP
    - APPLE
    - HAY_BLOCK
  25: # metal tools
    - GOLDEN_SWORD
    - GOLDEN_SHOVEL
    - GOLDEN_PICKAXE
    - GOLDEN_AXE
    - GOLDEN_HOE
    - DIAMOND_SWORD
    - DIAMOND_SHOVEL
    - DIAMOND_PICKAXE
    - DIAMOND_AXE
    - DIAMOND_HOE
    - GOLDEN_HELMET
    - GOLDEN_CHESTPLATE
    - GOLDEN_LEGGINGS
    - GOLDEN_BOOTS
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS
    - TURTLE_HELMET
  26: # special food
    - GOLDEN_APPLE
    - GOLDEN_CARROT
    - GLISTERING_MELON_SLICE
    - CAKE
  27: # tools
    - BOWL
    - CROSSBOW
    - SHEARS
    - FLINT_AND_STEEL
    - ARROW
    - ARMOR_STAND
    - MAP
    - ITEM_FRAME
    - GLOW_ITEM_FRAME
    - SPYGLASS
    - BUCKET
    - SHIELD
    - TRIPWIRE_HOOK
  28: # items craft
    - TNT
    - PAINTING
    - CAMPFIRE
    - LANTERN
    - CANDLE
    - HONEY_BLOCK
    - TRAPPED_CHEST
    - LIGHTNING_ROD
    - SCAFFOLDING
    - GLASS_PANE
    - LADDER
  29: # item find
    - SADDLE
    - BELL
    - GLOW_BERRIES
    - NAME_TAG
    - OBSIDIAN
    - CRYING_OBSIDIAN
    - SCUTE
  30: # bucket
    - MILK_BUCKET
    - WATER_BUCKET
    - LAVA_BUCKET
    - POWDER_SNOW_BUCKET
  31: # ocean
    - KELP
    - DRIED_KELP
    - DRIED_KELP_BLOCK
    - SEAGRASS
    - SEA_PICKLE
  32: # ground
    - GLASS_BOTTLE
    - POTION
    - GRAVEL
    - FLINT
    - DRIPSTONE_BLOCK
    - GLOW_LICHEN
    - POINTED_DRIPSTONE
  33: # flowers
    - DANDELION
    - POPPY
    - BLUE_ORCHID
    - ALLIUM
    - AZURE_BLUET
    - RED_TULIP
    - ORANGE_TULIP
    - WHITE_TULIP
    - PINK_TULIP
    - OXEYE_DAISY
    - CORNFLOWER
    - LILY_OF_THE_VALLEY
    - SUNFLOWER
    - LILAC
    - ROSE_BUSH
    - PEONY
  34: # sapling
    - OAK_SAPLING
    - SPRUCE_SAPLING
    - BIRCH_SAPLING
    - JUNGLE_SAPLING
    - ACACIA_SAPLING
    - DARK_OAK_SAPLING
  35: # wood
    #log
    - OAK_LOG
    - SPRUCE_LOG
    - BIRCH_LOG
    - JUNGLE_LOG
    - ACACIA_LOG
    - DARK_OAK_LOG
    # wood
    - OAK_WOOD
    - SPRUCE_WOOD
    - BIRCH_WOOD
    - JUNGLE_WOOD
    - ACACIA_WOOD
    - DARK_OAK_WOOD
    # stripped log
    - STRIPPED_OAK_LOG
    - STRIPPED_SPRUCE_LOG
    - STRIPPED_BIRCH_LOG
    - STRIPPED_JUNGLE_LOG
    - STRIPPED_ACACIA_LOG
    - STRIPPED_DARK_OAK_LOG
    # stripped wood
    - STRIPPED_OAK_WOOD
    - STRIPPED_SPRUCE_WOOD
    - STRIPPED_BIRCH_WOOD
    - STRIPPED_JUNGLE_WOOD
    - STRIPPED_ACACIA_WOOD
    - STRIPPED_DARK_OAK_WOOD
    # leaves
    - OAK_LEAVES
    - SPRUCE_LEAVES
    - BIRCH_LEAVES
    - JUNGLE_LEAVES
    - ACACIA_LEAVES
    - DARK_OAK_LEAVES
  36: # wood craft
    # slab
    - OAK_SLAB
    - SPRUCE_SLAB
    - BIRCH_SLAB
    - JUNGLE_SLAB
    - ACACIA_SLAB
    - DARK_OAK_SLAB
    # fence
    - OAK_FENCE
    - SPRUCE_FENCE
    - BIRCH_FENCE
    - JUNGLE_FENCE
    - ACACIA_FENCE
    - DARK_OAK_FENCE
    # stairs
    - OAK_STAIRS
    - SPRUCE_STAIRS
    - BIRCH_STAIRS
    - JUNGLE_STAIRS
    - ACACIA_STAIRS
    - DARK_OAK_STAIRS
    # door
    - OAK_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    # trapdoor
    - OAK_TRAPDOOR
    - SPRUCE_TRAPDOOR
    - BIRCH_TRAPDOOR
    - JUNGLE_TRAPDOOR
    - ACACIA_TRAPDOOR
    - DARK_OAK_TRAPDOOR
    # fence gate
    - OAK_FENCE_GATE
    - SPRUCE_FENCE_GATE
    - BIRCH_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - ACACIA_FENCE_GATE
    - DARK_OAK_FENCE_GATE
    # boat
    - OAK_BOAT
    - SPRUCE_BOAT
    - BIRCH_BOAT
    - JUNGLE_BOAT
    - ACACIA_BOAT
    - DARK_OAK_BOAT
    # sign
    - OAK_SIGN
    - SPRUCE_SIGN
    - BIRCH_SIGN
    - JUNGLE_SIGN
    - ACACIA_SIGN
    - DARK_OAK_SIGN
  37: # snow
    - SNOWBALL
    - SNOW_BLOCK
  38: # metal craft
    - IRON_DOOR
    - IRON_BARS
    - IRON_TRAPDOOR
    - ANVIL
    - CAULDRON
    - HOPPER
    - HEAVY_WEIGHTED_PRESSURE_PLATE
    - LIGHT_WEIGHTED_PRESSURE_PLATE
    - CHAIN
  39: # rail
    - RAIL
    - POWERED_RAIL
    - DETECTOR_RAIL
    - ACTIVATOR_RAIL
  40: # workstation
    - BLAST_FURNACE
    - SMOKER
    - CARTOGRAPHY_TABLE
    - ENCHANTING_TABLE
    - COMPOSTER
    - BARREL
    - FLETCHING_TABLE
    - LECTERN
    - STONECUTTER
    - LOOM
    - SMITHING_TABLE
    - GRINDSTONE
    - BEEHIVE
