name: Bingo
version: "0.0.2"
author: Ghomist
main: info.bcrc.mc.bingo.Bingo
api-version: 1.17
description: A bingo game plugin in Minecraft! Have fun!
commands:
  bingo:
    description: control bingo
    usage: |
      [Bingo Commands Usage]
      /bingo [setup|join|start|shutdown|playerlist]
      /bingo show information about this plugin
      /bingo setup [allcollect|shareinventory]: start a bingo in input mode(s)
      /bingo join [red|yellow|blue|green]: join the bingo after starting, as input team
      /bingo start: start the bingo
      /bingo shutdown: end the game forcibly
      /bingo playerlist: show the players joined the bingo
      /bingo help: show help
      /bingo check: check others' bingo map
      /bingo up: teleport the player up to the ground
    permission: bingo.default
    permission-message: You don't have <bingo.default>
permissions:
  bingo.default:
    description: Default permission in bingo plugin.
    default: true
